echo Begin to compile...
call gradlew assembleRelease
echo Compile succeeded.
echo Begin to install...
adb install -r ./build/outputs/apk/yibaotong.apk
echo Begin to launch...
adb shell am start -n "com.lzyc.ybtappcal/com.lzyc.ybtappcal.activity.LaunchActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
pause